# Week 1 — Student Grades Analysis

## Session 3 — NumPy Fundamentals

In [1]:
import numpy as np

grades = np.array([78, 85, 62, 91, 55, 88, 73, 69, 95, 81])

print(grades)
print(type(grades))

[78 85 62 91 55 88 73 69 95 81]
<class 'numpy.ndarray'>


In [2]:
# inspect the array
print("Number of dimensions:", grades.ndim)
print("Shape:", grades.shape)
print("Number of values:", grades.size)
print("Data type:", grades.dtype)

Number of dimensions: 1
Shape: (10,)
Number of values: 10
Data type: int64


In [3]:
# access NumPy array values
print("First grade:", grades[0])
print("Fourth grade:", grades[3])
print("Last grade:", grades[-1])

print("First three grades:", grades[:3])
print("Grades from position 3 to 6:", grades[3:7])

First grade: 78
Fourth grade: 91
Last grade: 81
First three grades: [78 85 62]
Grades from position 3 to 6: [91 55 88 73]


In [4]:
# basic NumPy calculations
print("Total:", grades.sum())
print("Average:", grades.mean())
print("Highest:", grades.max())
print("Lowest:", grades.min())

Total: 777
Average: 77.7
Highest: 95
Lowest: 55


In [5]:
# vectorized operations 
# The NumPy can perform one operation on every value without writting a loop.

adjusted_grades = grades + 5

print("Original grades:", grades)
print("Adjusted grades:", adjusted_grades)

percentage_grades = grades / 100

print("Percentage grades:", percentage_grades)

Original grades: [78 85 62 91 55 88 73 69 95 81]
Adjusted grades: [ 83  90  67  96  60  93  78  74 100  86]
Percentage grades: [0.78 0.85 0.62 0.91 0.55 0.88 0.73 0.69 0.95 0.81]


In [6]:
# comparison with NumPy

passing_mask = grades >= 50

print("Passing mask:", passing_mask)

# This create a Boolean array. Each position tell us whether the matching grade passes.

passing_grades = grades[passing_mask]

print("Passing grades:", passing_grades)
print("Number of passing grades:", passing_grades.size)

Passing mask: [ True  True  True  True  True  True  True  True  True  True]
Passing grades: [78 85 62 91 55 88 73 69 95 81]
Number of passing grades: 10


In [7]:
grades = np.array([78, 45, 62, 39, 91])

passing_mask = grades >= 50

print("Grades:", grades)
print("Mask:", passing_mask)
print("Passing grades:", grades[passing_mask])


Grades: [78 45 62 39 91]
Mask: [ True False  True False  True]
Passing grades: [78 62 91]


In [8]:
failing_mask = grades < 50
failing_grades = grades[failing_mask]

print("Failing mask:", failing_mask)
print("Failing grades:", failing_grades)

Failing mask: [False  True False  True False]
Failing grades: [45 39]


In [9]:
# count directly from the mask
print("Passing count:", passing_mask.sum())
print("Failing count:", failing_mask.sum())

Passing count: 3
Failing count: 2


In [10]:
# filter grades in a range

middle_mask = (grades >= 60) & (grades < 90)

middle_grades = grades[middle_mask]

print("Middle-range mask:", middle_mask)
print("Grades from 60 to 89:", middle_grades)

# replace values with np.where()
status_labels = np.where(grades >= 50, "Pass", "Fail")

print(status_labels)

Middle-range mask: [ True False  True False False]
Grades from 60 to 89: [78 62]
['Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [11]:
# sort the grades

sorted_grades = np.sort(grades)

print("Original grades:", grades)
print("Sorted grades:", sorted_grades)

Original grades: [78 45 62 39 91]
Sorted grades: [39 45 62 78 91]


In [12]:
# desecending order

desecending_grades = np.sort(grades)[::-1]
print("Grades from highest to lowest:", desecending_grades)

Grades from highest to lowest: [91 78 62 45 39]


In [13]:
# find the position of the highest and lowest grades
highest_index = grades.argmax()
lowest_index = grades.argmin()

print("Highest grade:", grades[highest_index])
print("Highest grade index:", highest_index)

print("Lowest grade:", grades[lowest_index])
print("Lowest grade index:", lowest_index)

Highest grade: 91
Highest grade index: 4
Lowest grade: 39
Lowest grade index: 3


In [14]:
#  basic spread of the grades
print("Mean:", grades.mean())
print("Median:", np.median(grades))
print("Standard deviation:", grades.std())

Mean: 63.0
Median: 62.0
Standard deviation: 19.544820285692065


In [15]:
# create a two-dimensional array
student_scores = np.array([
    [78, 85, 82],
    [45, 62, 55],
    [91, 88, 95]
])

print(student_scores)
print("Dimensions:", student_scores.ndim)
print("Shape:", student_scores.shape)
print("Size:", student_scores.size)

[[78 85 82]
 [45 62 55]
 [91 88 95]]
Dimensions: 2
Shape: (3, 3)
Size: 9


In [16]:
# access values in a 2D array
print("First student's first score:", student_scores[0, 0])
print("Second student's third score:", student_scores[1, 2])
print("Third student's second score:", student_scores[2, 1])

First student's first score: 78
Second student's third score: 55
Third student's second score: 88


In [20]:
# calculate averages by row and by column
student_averages = student_scores.mean(axis=1)
assignment_averages = student_scores.mean(axis=0)

print("Average for each student:", np.round(student_averages, 2))
print("Average for each assignment:", np.round(assignment_averages, 2))

Average for each student: [81.67 54.   91.33]
Average for each assignment: [71.33 78.33 77.33]


In [21]:
# find which students passed based on their average
student_status = np.where(student_averages >= 50, "Pass", "Fail")

print("Student averages:", np.round(student_averages, 2))
print("Student status:", student_status)

Student averages: [81.67 54.   91.33]
Student status: ['Pass' 'Pass' 'Pass']


In [22]:
performance_labels = np.where(
    student_averages >= 70,
    "Strong",
    "Needs Improvement"
)

print(performance_labels)

['Strong' 'Needs Improvement' 'Strong']


In [24]:
# find the highest student average
best_student_index = student_averages.argmax()

print("Best student index:", best_student_index)
print(
    "Best student average:",
    round(student_averages[best_student_index], 2)
)

Best student index: 2
Best student average: 91.33


In [40]:
import numpy as np

exam_scores = np.array([
    [82, 76, 91],
    [68, 59, 72],
    [95, 88, 93],
    [47, 52, 49]
])

# Averages
student_avg = np.round(exam_scores.mean(axis=1), 2)
exam_avg = np.round(exam_scores.mean(axis=0), 2)

# Passing / failing
passing_mask = student_avg >= 50
passing_students = passing_mask.sum()
failing_students = (~passing_mask).sum()

# Highest / lowest student averages
highest_avg = student_avg[np.argmax(student_avg)]
lowest_avg = student_avg[np.argmin(student_avg)]

print("Shape:", exam_scores.shape)
print("Number of scores:", exam_scores.size)
print("Average for each student:", student_avg)
print("Average for each exam:", exam_avg)
print("Passing students:", passing_students)
print("Failing students:", failing_students)
print("Highest student average:", highest_avg)
print("Lowest student average:", lowest_avg)

Shape: (4, 3)
Number of scores: 12
Average for each student: [83.   66.33 92.   49.33]
Average for each exam: [73.   68.75 76.25]
Passing students: 3
Failing students: 1
Highest student average: 92.0
Lowest student average: 49.33
